/**
 * Created by Jawad  on 08/08/2020.
 */

export const BrokerList: any = Object.assign({

    BROKER_LOGIN_STORE: 'BrokerLoginStore',
    BROKER_CLAIM_CONTROLLER_STORE: 'BrokerClaimControllerStore',
    BROKER_VEHICLE_SUMMARY_STORE: 'BrokerVehicleSummaryStore',
    BROKER_SEARCH_ACCIDENT_STORE: 'BrokerSearchAccidentStore',
    BROKER_WORKBASKET_STORE: 'BrokerWorkBasketStore',
    BROKER_REMOTESERVICES_STORE: 'BrokerRemoteServicesStore',
    BROKER_HTTP_FAILURE_STORE: 'BrokerHttpFailureStore',
    BROKER_ACTION_LOG_STORE: 'BrokerActionLogStore',
    BROKER_NOTIFICATION_STORE: 'BrokerNotificationStore',
    BROKER_FILE_URL_STORE: 'BrokerFileURLStore',
    BROKER_PDF_STORE: 'BrokerPdfStore',
    BROKER_ROUTER_STORE: 'BrokerRouterStore',
    BROKER_WORKBASKET_CONTROLLER_STORE: 'BrokerWorkbasketControllerStore',
    BROKER_FOOTER_CONTROLLER_STORE: 'BrokerFooterControllerStore',
    BROKER_HEADER_CONTROLLER_STORE: 'BrokerHeaderControllerStore',
    BROKER_ACCIDENT_CONTROLLER_STORE: 'BrokerAccidentControllerStore',
    BROKER_VEHICLE_CONTROLLER_STORE: 'BrokerVehicleControllerStore',
    BROKER_THIRD_PARTY_STORE: 'BrokerThirdPartyStore',
    BROKER_INITIAL_ASSESSMENT_CONTROLLER_STORE: 'BrokerInitialAssessmentControllerStore',
    BROKER_DIARY_CONTROLLER_STORE: 'BrokerDiaryControllerStore',
    BROKER_APPLICATION_PRINT_CONTROLLER_STORE: 'BrokerApplicationPrintControllerStore',
    BROKER_ATTACHMENT_CONTROLLER_STORE: 'BrokerAttachmentControllerStore',
    BROKER_PAYMENT_CONTROLLER_STORE: 'BrokerPaymentControllerStore',
    BROKER_APPLICATION_STORE: 'BrokerApplicationStore',
    BROKER_EVENTS_MAPPING_STORE: 'BrokerEventsMappingStore',
    BROKER_EVENT_HANDLER_STORE: 'BrokerEventHandlerStore',
    BROKER_IS_DIRTY_STORE: 'BrokerIsDirtyStore',
    BROKER_MEDICAL_EVIDENCE_CONTROLLER_STORE: 'BrokerMedicalEvidenceControllerStore',
    BROKER_FRAUD_CHECK_CONTROLLER_STORE: 'BrokerFraudCheckControllerStore',
    BROKER_INDEPENDENT_REVIEW_CONTROLLER_STORE: 'BrokerIndependentReviewControllerStore',
    BROKER_CLAIM_OFFER_CONTROLLER_STORE: 'BrokerClaimOfferControllerStore',
    BROKER_SEARCH_ACCIDENT_CONTROLLER_STORE: 'BrokerSearchAccidentControllerStore',
    BROKER_ACCIDENT_PHASE_VEHICLE_SECTION_CONTROLLER_STORE: 'BrokerAccidentPhaseVehicleSectionControllerStore',
    BROKER_ACCIDENT_PHASE_CLAIM_SECTION_CONTROLLER_STORE: 'BrokerAccidentPhaseClaimSectionControllerStore',
    BROKER_ACCIDENT_PHASE_DIARY_SECTION_CONTROLLER_STORE: 'BrokerAccidentPhaseDiarySectionControllerStore',
    BROKER_ACCIDENT_PHASE_ATTACHMENT_SECTION_CONTROLLER_STORE: 'BrokerAccidentPhaseAttachmentSectionControllerStore',
    BROKER_WEBSOCKETSERVICE_STORE: 'BrokerWebsocketServiceStore',
    BROKER_WEBSOCKET_MESSAGES_STORE: 'BrokerWebsocketMessagesStore',
    BROKER_SYSTEM_ADMIN_PAYMENT_STORE: 'BrokerPaymentsControllerStore',
    BROKER_SYSTEM_ADMIN_PARAMETERS_STORE: 'BrokerParametersControllerStore',
    BROKER_SYSTEM_ADMIN_DYNAMIC_FORMS_STORE: 'BrokerDynamicFormsControllerStore',
    BROKER_SYSTEM_ADMIN_SERVICE_PROVIDER_STORE: 'BrokerServiceProviderControllerStore',
    BROKER_SYSTEM_ADMIN_SYSTEM_USER_STORE: 'BrokerSystemUserControllerStore',
    BROKER_SYSTEM_ADMIN_BULK_ASSIGNMENT_STORE: 'BrokerBulkAssignmentControllerStore',
    BROKER_SYSTEM_ADMIN_GENERIC_RETRIEVE_STORE: 'BrokerGenericRetrieveControllerStore',
});
