export const GET_ACCIDENT_APP_ATTACHMENT_SECTION_BRIEF = '[AccidentPhaseAttachmentSectionController] Load AccidentPhaseAttachmentSectionBrief';
export const GET_ACCIDENT_APP_ATTACHMENT_SECTION_RECORD = '[AccidentPhaseAttachmentSectionController] Load AccidentPhaseAttachmentSectionSelectedRecord';
export const GET_ACCIDENT_APP_ATTACHMENT_SECTION_COMBO_DATA = '[AccidentPhaseAttachmentSectionController] Load AccidentPhaseAttachmentSectionComboData';


